# YAML Syntax Guide
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Config
title: Benjammin4dayz # The name of the site
description: Doing my own web dev. With Blackjack! # The description of the site; this is displayed in search engine results
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://benjammin4dayz.github.io' # the base hostname & protocol for your site, e.g. http://example.com

# Contact
email: your-email@example.com
twitter_username: benjammin4dayz
github_username: benjammin4dayz

# Build settings
plugins:
  - 'jekyll-github-metadata'
collections_dir: collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  pages:
    output: true
    permalink: /:path/
  dev:
    output: true
    permalink: /private/:path/
  redirects:
    output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - .gitignore
  - _projects/hyde/
